### ISSUE TITLE
support ancient database on a different volume

### ISSUE THREAD

**Issue by caevv** [eth-educators/eth-docker#1198]
I have an external HDD and would like to use `--datadir.ancient=/data-ancient`, but I would then need to change `geth.yml` and attach a new volume. Ideally we would be able to add a second volume for geth on .env.

**Comment by caevv** [comment]
Weird, even if I enable the way I say or directly all from geth.yml I keep getting panic:

```
execution_1                  | INFO [03-01|11:53:37.992] Allocated cache and file handles         database=/var/lib/goethereum/geth/chaindata cache=2.00GiB handles=524,288
execution_1                  | panic: runtime error: invalid memory address or nil pointer dereference
execution_1                  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb7e6e5]
execution_1                  |
execution_1                  | goroutine 1 [running]:
execution_1                  | github.com/ethereum/go-ethereum/core/rawdb.NewFreezer({0xc0007086f0, 0x21}, {0x194272f, 0x11}, 0x0, 0x0?, 0xc000695ce0?)
execution_1                  | 	github.com/ethereum/go-ethereum/core/rawdb/freezer.go:102 +0x165
execution_1                  | github.com/ethereum/go-ethereum/core/rawdb.NewChainFreezer(...)
execution_1                  | 	github.com/ethereum/go-ethereum/core/rawdb/freezer.go:85
execution_1                  | github.com/ethereum/go-ethereum/core/rawdb.newChainFreezer({0xc0007086f0?, 0x1b?}, {0x194272f?, 0xc000695d78?}, 0x78?)
```

```
  execution:
    restart: "unless-stopped"
    build:
      context: ./geth
      dockerfile: ${GETH_DOCKERFILE}
      args:
        - BUILD_TARGET=${GETH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${GETH_DOCKER_TAG}
    stop_grace_period: 5m
    image: geth:local
    user: geth
    environment:
      - JWT_SECRET=${JWT_SECRET:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - EL_EXTRAS=${EL_EXTRAS:-}
      - ARCHIVE_NODE=${ARCHIVE_NODE:-}
    volumes:
      - geth-eth1-data:/var/lib/goethereum
      - /etc/localtime:/etc/localtime:ro
      - jwtsecret:/var/lib/goethereum/ee-secret
      - geth-eth1-data-ancient:/var/lib/goethereum-ancient
    ports:
      - ${HOST_IP:-0.0.0.0}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - ${HOST_IP:-0.0.0.0}:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api
      - web3,eth,net
      - --datadir
      - /var/lib/goethereum
      - --datadir.ancient
      - /var/lib/goethereum-ancient
      - --port
      - ${EL_P2P_PORT:-30303}
      - --http.port
      - ${EL_RPC_PORT:-8545}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${EL_WS_PORT:-8546}
      - --ws.api
      - web3,eth,net
      - --${NETWORK}
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr
      - 0.0.0.0
      - --authrpc.jwtsecret
      - /var/lib/goethereum/ee-secret/jwtsecret
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - ${EE_PORT:-8551}
      - --authrpc.vhosts=*
      - --maxpeers
      - ${EL_MAX_PEER_COUNT:-50}

volumes:
  geth-eth1-data:
  jwtsecret:
  geth-eth1-data-ancient:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/wd/geth-data-ancient
```
