### ISSUE TITLE
besu CPU consumption slows down beaconchain node

### ISSUE THREAD

**Issue by jakrypto** [eth-educators/eth-docker#480]
Hello, I would like to share an issue with you. On my VPS with 10 vCPUs Besu was consuming so much CPU power during the sync process that the beaconchain node was in slots behind. I solved it as follows:
First, I added the following to besu.yml
```
services:
...
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 12288M
...
```

Next I rebuilt the image and started it with docker compose in compatibility mode:
`docker-compose --compatibility up -d execution`

Check if it has worked with:

`docker stats`

Maybe it helps somebody
