### ISSUE TITLE
Specify custom volumes destination

### ISSUE THREAD

**Issue by romanoLT** [eth-educators/eth-docker#957]
Hello, unless I have missed a configuration step or variable in the .env, I am not sure that the current version of eth-docker can let users define volumes with custom paths.
The use case is that you have a set of SSD mounted on your system but it's not part of the OS partition. Thus docker will use /var/lib/docker/ to store persistent data instead of your additional drives.

For example, in the XXX.yml files we can that volumes are specified like:
```
volumes:
  erigon-el-data:
  jwtsecret:
```

Ideally, what I described could be implemented like this: 
```
volumes:
  erigon-el-data:
     driver: local
     driver_opts:
        type: none
        o: bind
        device: ${EL_PATH:-"/var/lib/docker/.."}
  jwtsecret:
     driver: local
     driver_opts:
        type: none
        o: bind
        device: ${JWTSECRET_PATH:-"/var/lib/docker/.."}
```

There are other ways to do it, so happy to discuss the best approach if not already implemented.
thanks
